- src/components/FileTree/Tree.svelte
- src/components/FileTree/TreeStore.ts
- src/components/FileTree/TreeViewNodeList.svelte
- src/components/Sidebar/SidebarView.svelte
#10 enhancements added as per the change requirement 
Please find the SS.
> The file tree shouldnt have anything in it if there is no workspace loaded

- public/global.css
Fixes text being selectable on MacOS
> Added css propery for webkit

- package.json
- src/App.svelte
- src/components/Content/Editor/EditorTabs.svelte
- src/components/Content/Editor/Tab.svelte
- src/components/Sidebar/Sidebar.svelte
- src/components/Sidebar/Sidebar.ts
- src/components/Sidebar/SidebarView.svelte
- src/overrides.css
- yarn.lock
- Added package for managing editor layout via panels
- Rewrote code to fix sidebar resizing bug where it doesn't resize all the way if there are too many tabs open
- Fixes #26
> Editor Layout Rewrite

- src-tauri/src/main.rs
- src/components/Content/Editor/CodeMirrorEditor.svelte
- src/components/Content/Editor/scripts/Editor.ts
- src/components/Content/Editor/scripts/Tabs.ts
- src/components/FileTree/scripts/TreeData.ts
- src/components/Footer/Footer.svelte
Added line and column number detection for files.
Shows in the status bar.
> [Testing branch/Feature] Status Bar

- src/components/Content/Editor/Tabs.ts
- src/components/Menu/menu.ts
This implements #9 (ability to create new files)
- File > New now creates a new tab with title Untitled-<ID> 
- auto-saving is disabled for these tabs
- File > Save as lets the user choose a filename; afterwards, the tab title is switched to the new filename, and auto-saving is enabled
> Feature/add ability to create new file #9

- public/global.css
- src/components/Content/Editor/scripts/Tabs.ts
- src/components/Footer/Footer.svelte
- src/components/Footer/LanguageList.svelte
- src/components/Modal/RenameModel.svelte
- Language list shown after clicking the language on the bottom right corner
- Selected a language sets the file to the new language
- renaming a file with a new extension sets the file language based on the extension
> Language dropdown

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
- src/App.svelte
- src/components/Editor/CodeMirrorEditor.svelte
- src/components/Editor/scripts/DefaultTheme.ts
- src/components/FileTree/FileTree.svelte
- src/components/FileTree/scripts/TreeData.ts
- src/components/Footer/Footer.svelte
- src/components/Header/header_menus/FileMenu.ts
- src/components/Input/CheckmarkInput.svelte
- src/components/Input/Dropdown.svelte
- src/components/Input/NumberInput.svelte
- src/components/Settings/Settings.svelte
- src/components/Settings/SettingsTree.svelte
- src/components/Settings/settings/general/AppearanceSettings.svelte
- src/components/Tabs/EditorTabs.svelte
- src/components/Tabs/scripts/Tab.ts
- src/config/config.ts
- src/overrides.css
- src/scripts/EditorFile.ts
trying to get back in scope so hard
also added autosave toggle and notification addressing unsupported files (see #21)
> Testing branch

- src/config/themehandler.ts
- src/main.ts
Should point to the correct css file in prod build
> style: switched stylesheet load order

- .github/workflows/main.yml
- .github/workflows/publish.yml
Nightly builds should no longer be a release
Updated workflow to make releases on push to release branch instead of master
> Dev: chore(workflow): attempting to fix workflows 

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src/lib/File.ts
- src/lib/FileTree/FileTreeList.svelte
- src/lib/FileTree/FileTreeView.svelte
- src/lib/Settings.svelte
- src/lib/SidebarView.svelte
- src/lib/utility/ProgressBar.svelte
I'm too lazy to type this just look at the commit messages
> Alpha v0.2

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/tauri.conf.json
- src/config/commands.ts
- src/lib/Editor.svelte
- src/lib/Header.svelte
> Bug fixes for alpha v0.2.1

- src/lib/Header.svelte
- src/lib/utility/Dropdown.svelte
fix: #96 
- Implements switching of menus on hover when there is any menu open
https://github.com/mellobacon/Nucleus/assets/70792552/baf40e60-1f24-4d02-bb8a-e411738e57a6
> Switching of menus on hover when there is any menu open

- src/lib/Header.svelte
- src/lib/utility/Dropdown.svelte
> Revert "Switching of menus on hover when there is any menu open"

- src-tauri/Cargo.toml
- src/config/syntaxhighlighting/dark.ts
- src/lib/Editor.svelte
- src/lib/Tab/Tab.ts
Added basic syntax highlighting based on OneDark theme.
> Feat: syntax highlighting

- README.md
- src-tauri/src/main.rs
- src/App.svelte
- src/config/commands.ts
- src/lib/File.ts
- src/lib/FileTree.svelte
- src/lib/FileTree/FileTreeList.svelte
- src/lib/FileTree/FileTreeNode.svelte
- src/lib/Modals/InputModal.svelte
- src/lib/Modals/RenameModal.svelte
- src/lib/utility/Input.svelte
- fixes #113 
- other qol fixes
> A bunch of fixes

- .github/workflows/main.yml
- release build to be made on push to master instead of release branch
> chore(workflow): updated workflow to make release build

- src/lib/Modals/RenameModal.svelte
> chore: removed file input box from rename model

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/tauri.conf.json
- src/App.svelte
- src/global.css
- src/lib/Statusbar.svelte
- src/lib/Tab/TabList.svelte
- src/lib/ToolView.svelte
- src/theme.scss
bottom panel can be toggled from statusbar
> feat: added bottom panel 

- src-tauri/src/main.rs
- src/lib/Editor.svelte
- src/lib/Statusbar.svelte
- src/theme.scss
clicking the terminal button on the status bar should open an external terminal window
> feat: added external terminal support

- src/App.svelte
- src/lib/Header.svelte
- src/lib/Welcome.svelte
- functional new file, open folder, config shortcuts
- shows version info
> Added welcome tab

- src/config/commands.ts
- src/lib/File.ts
- src/lib/FileTree.svelte
- src/lib/Welcome.svelte
- src/lib/utility/RecentFolders.svelte
- Recent folders popup added
- Popup can be triggered from welcome page
> Recent folders
